name: Build Chinese APK (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK (Auto-signed)
        run: ./gradlew assembleDebug

      - name: Upload APKs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mpvEx-Chinese-APKs
          path: app/build/outputs/apk/**/*.apk
